### PR TITLE
Display the host and port anyblok_pyramid is running at

### PR DESCRIPTION
**Pull request by franckbret**
When anyblok_pyramid is launched, the only way to see the host and port it is actually running as is to set the --logging-level=INFO or DEBUG 

The problem is that when going INFO or DEBUG mode we got a lot of trace because it logs sqlalchemy.

The patch set to warning the logging message when anyblok_pyramid start that indicate the host and port the server is running at.
As it is for local development, I don't see any cons in doing so, the message is returned as is (without warning). This way it works in all case.

### CODE REVIEW

**Comment by jssuzanne** [comment]
For me, it is a wrong issue

1) It is an info not a warning
2) You can correct it with another logging configuration

```
[loggers]
keys = root, anyblok_pyramid, anyblok_pyramid_scripts

[handlers]
keys = consoleHandler

[formatters]
keys = consoleFormatter

[logger_root]
level = INFO
handlers = consoleHandler

[logger_anyblok_pyramid]
level = WARNING
handlers = consoleHandler
qualname = anyblok_pyramid
propagate = 0

[logger_anyblok_pyramid_scripts]
level = INFO
handlers = consoleHandler
qualname = anyblok_pyramid.scripts
propagate = 0

[handler_consoleHandler]
class = StreamHandler
formatter = consoleFormatter
args = (sys.stdout,)

[formatter_consoleFormatter]
class = anyblok.logging.consoleFormatter
format = %(database)s:%(levelname)s - %(name)s:%(message)s
datefmt =
```

**Comment by franckbret** [comment]
Ok, thanks for your example,  i know i can tweak logging and i do in my projects.
In this case maybe a print statement is sufficient

**Comment by jssuzanne** [comment]
Yep add a print and logging.info can be a good point

**Comment by franckbret** [comment]
@jssuzanne thsi one looks good but fails with py 3.8-dev, this is a gcc/lxml issue, I don't know how to resolve this...

**Comment by franckbret** [comment]
@jssuzanne I've done the same as we do in Anyblok travis configuration file, allow failures on python3.7-dev and python3.8-dev.

**Comment by jssuzanne** [comment]
> @jssuzanne thsi one looks good but fails with py 3.8-dev, this is a gcc/lxml issue, I don't know how to resolve this...

It is a dev version, we should wait before to do any action

**Pull request merged**
